---
title: "PS270 Final Project"
author: "Joseph Kutrieb"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts
My research question is how do age and education impact a person's participation in election opinion polls? My hypothesis is that older and more educated people participate at a higher rate in election opinion polls than younger and less educated people. I hypothesize this because older and more educated people generally have more time to participate in these and may have more interest. Someone who is older and possibly retired with a higher education level will have more time and knowledge/interest to participate in an election opinion poll. However, a younger people with a lower education level might have less time to participate and less interest. My explanatory variables are age and education and these are measured by a person's age and the highest level of education they have completed. The outcome variable is the rate of participation of different groups of people in election opinion polls. This can be measured by seeing what proportion of people who participate are above or below a certain age or a certain level of education. Something that would support my hypothesis would be seeing groups of people who are older and more educated participating more in these polls than people who are younger and less educated. However, if I see that younger people with less education are participating more than I will see that my hypothesis is false.

```{r}
library(tidyverse)
data <- read_csv("ATP W153.csv")
head(data)
```

